.PHONY: build run flash build-py run-py flash-py

build:
	./scripts/build.sh

run:
	./scripts/run.sh

flash:
	./scripts/flash.sh

build-py:
	python3 ./scripts/build.py

run-py:
	python3 ./scripts/run.py

flash-py:
	python3 ./scripts/flash.py
